// Code generated by MockGen. DO NOT EDIT.
// Source: helper.go

// Package mock_gomockk is a generated GoMock package.
package mock_gomockk

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRequester is a mock of Requester interface
type MockRequester struct {
	ctrl     *gomock.Controller
	recorder *MockRequesterMockRecorder
}

// MockRequesterMockRecorder is the mock recorder for MockRequester
type MockRequesterMockRecorder struct {
	mock *MockRequester
}

// NewMockRequester creates a new mock instance
func NewMockRequester(ctrl *gomock.Controller) *MockRequester {
	mock := &MockRequester{ctrl: ctrl}
	mock.recorder = &MockRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRequester) EXPECT() *MockRequesterMockRecorder {
	return m.recorder
}

// Crawl mocks base method
func (m *MockRequester) Crawl(url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Crawl", url)
	ret0, _ := ret[0].(string)
	return ret0
}

// Crawl indicates an expected call of Crawl
func (mr *MockRequesterMockRecorder) Crawl(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Crawl", reflect.TypeOf((*MockRequester)(nil).Crawl), url)
}
